//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddtoCartmodule.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BUser()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int BUser_id { get; set; }
        public string BUser_name { get; set; }
        public string BUser_email { get; set; }
        public string BUser_password { get; set; }
        public int BUser_contactno { get; set; }
        public string BUser_Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
