//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddtoCartmodule.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AddtocartmoduleEntities : DbContext
    {
        public AddtocartmoduleEntities()
            : base("name=AddtocartmoduleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BTransaction> BTransactions { get; set; }
        public virtual DbSet<BUser> BUsers { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
    }
}
